# Generated by Django 2.0.1 on 2018-01-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
