# Generated by Django 2.0.1 on 2018-03-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180224_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
            preserve_default=False,
        ),
    ]
